name: 'group04'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - ipykernel
  - nb_conda_kernels
  - altair-all=5.4.*
  - vega_datasets
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - eli5
  - shap
  - jinja2
  - lightgbm
  - spacy
  - xgboost
  - catboost
  - nltk
  - imbalanced-learn
  - pip:
    - mglearn
    - spacymoji
    - altair_ally>=0.1.1