name: 'group04'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.3.1
  - ipykernel=6.29.5
  - altair-all=5.4.*
  - vega_datasets=0.9.0
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - scipy=1.14.1
  - matplotlib>=3.2.2
  - scikit-learn=1.5.2
  - requests>=2.24.0
  - graphviz=12.0.0
  - python-graphviz=0.20.3
  - eli5=0.13.0
  - shap=0.46.0
  - jinja2=3.1.4
  - lightgbm=4.5.0
  - spacy=3.8.2
  - imbalanced-learn=0.12.4
  - conda-lock=2.5.7
  - pip:
    - altair_ally>=0.1.1